"""empty message

Revision ID: c59030b19be4
Revises: e30cfe1f09e0
Create Date: 2022-10-31 23:52:56.432198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59030b19be4'
down_revision = 'e30cfe1f09e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.String(length=250), nullable=True),
    sa.Column('rotational_period', sa.String(length=250), nullable=True),
    sa.Column('orbital_period', sa.String(length=250), nullable=True),
    sa.Column('gravity', sa.String(length=250), nullable=True),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('climate', sa.String(length=250), nullable=True),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.Column('surface_water', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.Column('starship_class', sa.String(length=250), nullable=True),
    sa.Column('manufactuer', sa.String(length=250), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=250), nullable=True),
    sa.Column('length', sa.String(length=250), nullable=True),
    sa.Column('crew', sa.String(length=250), nullable=True),
    sa.Column('passengers', sa.String(length=250), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=250), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(length=250), nullable=True),
    sa.Column('MGLT', sa.String(length=250), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=250), nullable=True),
    sa.Column('consumables', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=True),
    sa.Column('home_world_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_world_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_name', sa.String(length=250), nullable=True),
    sa.Column('favorite_planet_id', sa.Integer(), nullable=True),
    sa.Column('favorite_character_id', sa.Integer(), nullable=True),
    sa.Column('favorite_starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorite_planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['favorite_starship_id'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=250), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               nullable=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('favorite')
    op.drop_table('character')
    op.drop_table('starship')
    op.drop_table('planet')
    # ### end Alembic commands ###
